service: household-expenses

plugins:
  - serverless-python-requirements
  - serverless-prune-plugin
custom:
  pythonRequirements:
    dockerizePip: true
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  runtime: python3.8
  role: yourRole
  timeout: 900
  stage: dev
  region: yourRegion
  profile: yourProfile
  deploymentBucket:
    name: yourBucket


functions:

  get_expenses:
    handler: alerts.alert_handler
    memorySize: 256
    events:
      - schedule: cron(0 17 ? * SUN *)